name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install requests
        pip install pillow
        pip install mysql-connector-python
    
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')
    
    - name: Run tests with unittest
      run: |
        python -m unittest score_test.py
        python -m unittest database_manager_test.py
